language: generic
env:
  - HUGO_VERSION=0.36.1

install:
  - wget https://github.com/gohugoio/hugo/releases/download/v${HUGO_VERSION}/hugo_${HUGO_VERSION}_Linux-64bit.tar.gz
  - tar -xvf hugo_${HUGO_VERSION}_Linux-64bit.tar.gz hugo

script:
  - ./hugo

deploy:
  provider: pages
  skip_cleanup: true
  github_token: ${GH_TOKEN}
  local_dir: public
